# run:    conda env create -f environment.yml
# update: conda env update -f environment.yml
name: my-project-envname
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7
  - anaconda
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - pip
  - jupyter
